language: java
jdk:
  - oraclejdk8

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y build-essential python-opencv
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y ffmpeg libavutil-dev libavcodec-dev libavfilter-dev libavformat-dev libavdevice-dev
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install -y libopencv-dev

before_script:
  - git clone https://github.com/opencv/opencv
  - cd opencv
  - git checkout 3.2.0
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - ls -l /usr/local/share/OpenCV/java/libopencv_java320.so
  - sudo mkdir -p /usr/java/packages/lib/amd64
  - ls -l /usr/java/packages/lib/amd64/
  - sudo cp /usr/local/share/OpenCV/java/libopencv_java320.so /usr/java/packages/lib/amd64/libopencv_java320.so
  - sudo cp /usr/local/share/OpenCV/java/libopencv_java320.so /usr/java/packages/lib/amd64/opencv_java320.so
  - cd ../..
