language: java
jdk:
  - oraclejdk8

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y ffmpeg libavutil-dev libavcodec-dev libavfilter-dev libavformat-dev libavdevice-dev
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install -y python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
  - sudo apt-get install -y ninja-build

before_script:
  - git clone https://github.com/opencv/opencv
  - cd opencv
  - git checkout 3.2.0
  - mkdir build
  - cd build
  - cmake -GNinja ..
  - ninja
  - cd ../..
